<a href="https://colab.research.google.com/github/omkarmm19/Python-Essentials/blob/main/Module11.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
x=np.arange(4)
print("x    =",x)
print("x + 5=",x + 5)
print("x - 5=",x - 5)
print("x * 2=",x * 2)
print("x / 2=",x / 2)
print("x // 2=",x // 2)
print("-x    =",-x)
print("x ** 2=",x ** 2)
print("x % 2=",x % 2)

x    = [0 1 2 3]
x + 5= [5 6 7 8]
x - 5= [-5 -4 -3 -2]
x * 2= [0 2 4 6]
x / 2= [0.  0.5 1.  1.5]
x // 2= [0 0 1 1]
-x    = [ 0 -1 -2 -3]
x ** 2= [0 1 4 9]
x % 2= [0 1 0 1]


In [ ]:
import numpy as np
x=np.arange(5)
y=np.empty(5)
np.multiply(x,10,out=y)
print(y)

[ 0. 10. 20. 30. 40.]


In [ ]:
import numpy as np
x=np.arange(9).reshape((3,3))
print(x)
print(2**x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[  1   2   4]
 [  8  16  32]
 [ 64 128 256]]


In [ ]:
import numpy as np
x=[1,2,3]
print("x    =",x)
print("e^x  =",np.exp(X))
print("2^x  =",np.exp2(X))
print("3^x  =",np.power(3,X))

x    = [1, 2, 3]


NameError: ignored

In [ ]:
import numpy as np
x=[1,2,4,10]
print("x    =",x)
print("ln(x)   =",np.log(X))
print("log2(x) =",np.log2(X))
print("log10(x)=",np.log10(3,X))


x    = [1, 2, 4, 10]


NameError: ignored

In [ ]:
import numpy as np
x=[1,2,3,4]
y=[4,5,6,7]
z=np.add(x,y)
print(z)

[ 5  7  9 11]


In [ ]:
from array import*
array1=array('i',[10,20,30,40,50])
array1.insert(2,600)
for x in array1:
  print(x)

10
20
600
30
40
50


In [ ]:
from array import*
array1=array('i',[10,20,30,40,50])
array1.remove(40)
for x in array1:
  print(x)

10
20
30
50


In [ ]:
import array as A
arr=A.array('i',[1,2,3,4,5])
print("Array elements:",arr)
print("Length of array:",len(arr))

Array elements: array('i', [1, 2, 3, 4, 5])
Length of array: 5


In [ ]:
array=[10,20,30,40,50];
print("Here is the original array:");
for i in range(0,len(array)):
  print(array[i]),
  print("Here is array in reverse order:");
for i in range(len(array)-1,-1,-1):
  print(array[i])

Here is the original array:
10
Here is array in reverse order:
20
Here is array in reverse order:
30
Here is array in reverse order:
40
Here is array in reverse order:
50
Here is array in reverse order:
50
40
30
20
10


In [ ]:
arr=[10,25,12,17,79,53];
max=arr[0];
for i in range(1,len(arr)):
  if(arr[i]>max):
    max=arr[i];
    print("Largest element is given array=",max)

Largest element is given array= 25
Largest element is given array= 79


In [ ]:
import numpy as np
x=np.array([5,1,4,2,3,7])
print("Sum:",np.sum(x))
print("Max:",np.max(x))
print("Index of Max Element:",np.argmax(x))
print("Index of Min Element:",np.argmin(x))
print("Min:",np.min(x))
print("Mean:",np.mean(x))
print("Standard Deviation:",np.std(x))
print("Variance:",np.var(x))
print("Product:",np.prod(x))
print("25th Percentile:",np.percentile(x,25))
print("75th Percentile:",np.percentile(x,75))

Sum: 22
Max: 7
Index of Max Element: 5
Index of Min Element: 1
Min: 1
Mean: 3.6666666666666665
Standard Deviation: 1.9720265943665387
Variance: 3.8888888888888893
Product: 840
25th Percentile: 2.25
75th Percentile: 4.75


In [ ]:
x=np.array([1,2,3,4,5])
x<3

array([ True,  True, False, False, False])

In [ ]:
x>3

array([False, False, False,  True,  True])

In [ ]:
x>=3

array([False, False,  True,  True,  True])

In [ ]:
x!=3

array([ True,  True, False,  True,  True])

In [ ]:
x==3

array([False, False,  True, False, False])

In [ ]:
import numpy as np
x=np.array([1,2,3,4,5])
print(np.equal(x,3))
print(np.not_equal(x,3))
print(np.less(x,3))
print(np.greater(x,3))
print(np.less_equal(x,3))
print(np.greater_equal(x,3))


[False False  True False False]
[ True  True False  True  True]
[ True  True False False False]
[False False False  True  True]
[ True  True  True False False]
[False False  True  True  True]


In [ ]:
rng=np.random.RandomState(1)
x=rng.randint(10,size=(3,4))
print(x)
print(np.count_nonzero(x<6))
print(np.sum(x<6))
print(np.any(x<0))
print(np.all(x<10))

[[5 8 9 5]
 [0 0 1 7]
 [6 9 2 4]]
7
7
False
True


In [32]:
import numpy as np
print('---numpy logical_and operator Example---')
print('True logical_and True =',np.logical_and(True,True))
print('True logical_and False =',np.logical_and(True,False))
print('False logical_and True =',np.logical_and(False,True))
print('False logical_and False =',np.logical_and(False,False))

---numpy logical_and operator Example---
True logical_and True = True
True logical_and False = False
False logical_and True = False
False logical_and False = False


In [33]:
import numpy as np
x=np.array([5,1,4,2,3,7])
print(np.bitwise_or(x,2))
print(np.bitwise_xor(x,2))
print(np.bitwise_not(x))

[7 3 6 2 3 7]
[7 3 6 0 1 5]
[-6 -2 -5 -3 -4 -8]


In [34]:
print(bin(43))
print(bin(43 & 58))
print(bin(43 | 58))


0b101011
0b101010
0b111011


In [35]:
import numpy as np
x=np.array([51,15,4,24,36,71])
print(x)
[x[0],x[3],x[2]]


[51 15  4 24 36 71]


[51, 24, 4]

In [36]:
import numpy as np
x=np.array([51,15,4,24,36,71])
print(x)
ind=[3,4,2]
print(x[ind])


[51 15  4 24 36 71]
[24 36  4]


In [37]:
import numpy as np
x=np.array([21,1,4,13,5])
print(np.sort(x))

[ 1  4  5 13 21]


In [38]:
import numpy as np
x=np.array([21,1,4,13,5])
i=np.argsort(x)
print("Array Index:",i)
print("Array Elements:",x[i])

Array Index: [1 2 4 3 0]
Array Elements: [ 1  4  5 13 21]


In [51]:
import numpy as np
name=['Joe','Alice','Bob','Cathy']
weight=[55.5,85.5,68.0,61.5]
data=np.zeros(4,dtype={'names':('name','age','weight'),'formats':('U10','i4','f8')})
print(data.dtype)
data['name']=name
data['age']=age
data['weight']=weight
print(data)

[('name', '<U10'), ('age', '<i4'), ('weight', '<f8')]


NameError: ignored

In [46]:
data['name']

array(['', '', '', ''], dtype='<U10')

In [53]:
data[0]

('Joe', 0, 0.)

In [54]:
data[-1]['name']

'Cathy'

In [55]:
data[data['age']<30]['name']

array(['Joe', 'Alice', 'Bob', 'Cathy'], dtype='<U10')